# 'Essen & Trinken': ['fast-food', 'restaurant', 'biergarten', 'cafe', 'bar', 'pub'],
# 'Freizeit': ['cinema', 'arts-centre', 'nightclub', 'sauna', 'theatre'],
# 'Geld': ['bank', 'atm', 'bureau-de-change'],
# 'Post': ['post-box', 'post-office'],
# 'Botschaften & Behörden': ['embassy', 'courthouse', 'police', 'fire-station', 'public-building', 'register-office', 'townhall', 'community-centre'],
# 'Medizin': ['hospital', 'pharmacy'],
# 'Auto & Fahrrad': ['fuel', 'car-rental', 'car-sharing', 'parking', 'bicycle-parking', 'bicycle-rental'],
# 'Kinder & Bildung': ['kindergarten', 'school', 'college', 'university', 'library'],
# 'Sonstiges': ['marketplace', 'telephone', 'toilets', 'grave-yard', 'place-of-worship']

WheelchairStatus = %w{yes limited no unknown}

Amenities = {
  :public_transfer => %w{subway aerodrome bicycle_rental bus_station bus_stop ferry ferry_terminal halt platform subway_entrance terminal tram_stop parking_aisle fuel parking car_rental car_sharing boatyard cable_car chair_lift},
  :food => %w{cafe pub restaurant fast_food drinking_water},
  :leisure => %w{cinema theatre zoo nightclub gallery arena},
  :money_post => %w{post_office atm bank bureau_de_change},
  :education => %w{college  library school university museum kindergarten},
  :shopping => %w{supermarket hairdresser clothes mall furniture electronics books beverages alcohol department_store shoes hardware garden_centre optician computer bakery},
  :sport => %w{stadium sports_centre swimming_pool swimming},
  :tourism => %w{archaeological_site arts_centre artwork battlefield beacon theme_park attraction beach viewpoint tower memorial information cave_entrance castle},
  :accommodation => %w{chalet hostel hotel motel camp_site guest_house caravan_site bed_and_breakfast beach_resort},
  :misc => %w{place_of_worship hospital doctors pharmacy veterinary toilets},
  :government => %w{courthouse public_building townhall}
}

Tags = {
  :aerodrome => :aeroway,
  :alcohol => :shop,
  :archaeological_site => :historic,
  :arena => :leisure,
  :arts_centre => :amenity,
  :artwork => :amenity,
  :atm => :amenity,
  :attraction => :tourism,
  :bakery => :shop,
  :bank => :amenity,
  :battlefield => :historic,
  :beach => :natural,
  :beach_resort => :leisure,
  :beacon => :man_made,
  :bed_and_breakfast => :tourism,
  :beverages => :shop,
  :bicycle_rental => :amenity,
  :boatyard => :waterway,
  :books => :shop,
  :bureau_de_change => :amenity,
  :bus_station => :amenity,
  :bus_stop => :highway,
  :cable_car => :aerialway,
  :cafe => :amenity,
  :camp_site => :tourism,
  :caravan_site => :tourism,
  :car_rental => :amenity,
  :car_sharing => :amenity,
  :castle => :historic,
  :cave_entrance => :natural,
  :chair_lift => :aerialway,
  :chalet => :tourism,
  :cinema => :amenity,
  :clothes => :shop,
  :college => :amenity,
  :computer => :shop,
  :courthouse => :amenity,
  :department_store => :shop,
  :doctors => :amenity,
  :drinking_water => :amenity,
  :electronics => :shop,
  :fast_food => :amenity,
  :ferry => :route,
  :ferry_terminal => :amenity,
  :fuel => :amenity,
  :furniture => :shop,
  :gallery => :amenity,
  :garden_centre => :shop,
  :guest_house => :tourism,
  :hairdresser => :shop,
  :halt => :railway,
  :hardware => :shop,
  :hospital => :amenity,
  :hostel => :tourism,
  :hotel => :tourism,
  :information => :tourism,
  :kindergarten => :amenity,
  :library => :amenity,
  :mall => :shop,
  :memorial => :historic,
  :motel => :tourism,
  :museum => :tourism,
  :nightclub => :amenity,
  :optician => :shop,
  :parking => :amenity,
  :parking_aisle => :amenity,
  :pharmacy => :shop,
  :place_of_worship => :amenity,
  :platform => :railway,
  :post_office => :amenity,
  :pub => :amenity,
  :public_building => :amenity,
  :restaurant => :amenity,
  :school => :amenity,
  :shoes => :shoes,
  :sports_centre => :leisure,
  :stadium => :leisure,
  :subway => :railway,
  :subway_entrance => :railway,
  :supermarket => :shoes,
  :swimming => :sport,
  :swimming_pool => :leisure,
  :terminal => :aeroway,
  :theatre => :amenity,
  :theme_park => :tourism,
  :toilets => :amenity,
  :tower => :power,
  :townhall => :amenity,
  :tram_stop => :railway,
  :university => :amenity,
  :veterinary => :amenity,
  :viewpoint => :tourism,
  :zoo => :tourism
}